language: bash

arch:
  - amd64
  - ppc64le

os: linux

dist: xenial


services:
  - docker

before_install:
  - docker image ls
  - docker pull ubuntu:18.04

script:
  - echo $TRAVIS_CPU_ARCH
  - uname -a
  - which bash
  - file /bin/bash
  - cat /etc/os-release
  - id
  - cat /proc/1/cgroup
  - docker image ls
  - docker run ubuntu:18.04  uname -a
  - docker run ubuntu:18.04  which bash
  - docker run ubuntu:18.04  cat /etc/os-release
  - docker run ubuntu:18.04  id
  - docker run ubuntu:18.04  cat /proc/1/cgroup

