os: linux
dist: bionic
arch:
  - amd64
  - ppc64le

sudo: required

#language: c
language: bash

services:
  - docker

env:
  global:
    - FOO=global
  matrix:
    - BAR=arch_all
    - BAR=arch_ppc64le
    - BAR=arch_amd64
    - BAR=arch_ppc64le FOO=local

script:
  - echo "ARCH & basic info"
  - echo $TRAVIS_CPU_ARCH
  - hostname
  - uname -a
  - which bash
  - file /bin/bash
  - cat /etc/os-release
  - id
  - echo "FOO=$FOO  BAR=$BAR"
