os: linux
dist: bionic
arch:
  - ppc64le
  - amd64

sudo: required

#language: c
language: bash

services:
  - docker

env:
  global:
    - FOO=global
  matrix:
    - BAR=arch_all

matrix:
  include:
    - env: BAR=arch_amd64
      arch: amd64
    - env: BAR=arch_ppc64le
      arch: ppc64le
    - env: BAR=arch_ppc64le FOO=local

script:
  - echo "ARCH & basic info"
  - echo $TRAVIS_CPU_ARCH
  - hostname
  - uname -a
  - which bash
  - file /bin/bash
  - cat /etc/os-release
  - id
  - echo "FOO=$FOO  BAR=$BAR"
  - sudo dmesg
