language: bash

arch:
  - amd64
  - ppc64le

os: linux

dist: xenial


services:
  - docker

before_install:
  - docker pull ubuntu:18.04

script:
  - echo $TRAVIS_CPU_ARCH
  - uname -a
  - file /bin/bash
  - cat /etc/os-release
  - id
  - docker run ubuntu:18.04  cat /etc/os-release

